### ISSUE TITLE
Would you be open for an extend?

### ISSUE THREAD

**Issue by janw-me** [Miller-Media/expire-passwords#11]
For our company we want a password reset without the email.
Would you be open if I would develop this in a pull request?

My top 2 references: [Default featured image](https://wordpress.org/plugins/default-featured-image/) && [Disable Full Site Editing](https://github.com/janw-me/disable-full-site-editing).

**Comment by mattmillerai** [comment]
Yes I'd be open to that. I would say that this should be added as a setting on the settings page that defaults to the current behavior. Thanks!

**Comment by janw-me** [comment]
Thanks I'll let you know when I've worked on it.

**Comment by mattmillerai** [comment]
PR approved and merged. Thank you!

**Comment by janw-me** [comment]
Thank you :)
